package ghmirror

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mlnomadpy/dacli/internal/agentid"
	"github.com/mlnomadpy/dacli/internal/clikit"
	"github.com/mlnomadpy/dacli/internal/store"
	"github.com/mlnomadpy/dacli/internal/team"
	"github.com/mlnomadpy/dacli/internal/workspace"
)

// unsetAgentEnv clears DACLI_AGENT for the test, restoring whatever the
// process started with. t.Setenv cannot unset a variable, and since dacli 288
// a present-but-empty DACLI_AGENT is a lost token that fails closed rather
// than resolving to root — so a test wanting the root identity must remove
// the variable entirely, not blank it.
func unsetAgentEnv(t *testing.T) {
	t.Helper()
	if v, ok := os.LookupEnv(agentid.EnvVar); ok {
		t.Setenv(agentid.EnvVar, v)
		_ = os.Unsetenv(agentid.EnvVar)
	}
}

// A dacli scope glob's trailing /** is redundant under CODEOWNERS's recursive
// directory matching and is stripped; a bare ** (or empty) becomes *; anything
// else passes through so a pattern CODEOWNERS cannot express is not mistranslated.
func TestCodeownersPattern(t *testing.T) {
	cases := map[string]string{
		"internal/**":                    "internal/",
		"internal/features/dashboard/**": "internal/features/dashboard/",
		"**":                             "*",
		"":                               "*",
		"web/app.go":                     "web/app.go",
	}
	for in, want := range cases {
		if got := codeownersPattern(in); got != want {
			t.Errorf("codeownersPattern(%q) = %q, want %q", in, got, want)
		}
	}
}

// Two roles owning the same pattern must share ONE line (CODEOWNERS's multi-owner
// form), and patterns must be emitted most-general-first so a specific owner
// overrides a broad one under last-match-wins. A role with no scope is skipped.
func TestCodeownersEntriesGroupsAndOrders(t *testing.T) {
	roles := []team.Role{
		{Name: "go-auditor", Scope: []string{"internal/**"}},
		{Name: "frontend-reviewer", Scope: []string{"internal/features/dashboard/**"}},
		{Name: "maintainer", Scope: []string{"internal/**"}}, // co-owns internal/
		{Name: "no-scope"}, // skipped
	}
	entries := codeownersEntries(roles, "acme")
	if len(entries) != 2 {
		t.Fatalf("got %d entries, want 2 (grouped by pattern): %+v", len(entries), entries)
	}
	// Most-general (shortest) first.
	if entries[0].Pattern != "internal/" {
		t.Fatalf("first pattern = %q, want the broadest 'internal/' first", entries[0].Pattern)
	}
	if entries[1].Pattern != "internal/features/dashboard/" {
		t.Fatalf("second pattern = %q, want the specific one last", entries[1].Pattern)
	}
	// internal/ is co-owned; owners merged onto one line, deduped, order kept.
	want := []string{"@acme/go-auditor", "@acme/maintainer"}
	if strings.Join(entries[0].Owners, ",") != strings.Join(want, ",") {
		t.Fatalf("internal/ owners = %v, want %v (merged, deduped, ordered)", entries[0].Owners, want)
	}
}

// The rendered file carries the generated-by header and one pattern→owner line.
func TestCodeownersDoc(t *testing.T) {
	doc := codeownersDoc([]codeownersEntry{{Pattern: "internal/", Owners: []string{"@acme/go-auditor"}}})
	if !strings.Contains(doc, "generated by dacli") {
		t.Fatalf("CODEOWNERS must carry a generated-by header so it is not hand-edited:\n%s", doc)
	}
	if !strings.Contains(doc, "internal/ @acme/go-auditor") {
		t.Fatalf("CODEOWNERS missing the pattern→owner line:\n%s", doc)
	}
}

// End-to-end: the command writes .github/CODEOWNERS mapping a role's scope to a
// team handle under --owner, without needing gh or a linked repo.
func TestCmdCodeownersWritesFile(t *testing.T) {
	unsetAgentEnv(t) // this suite may run as a dacli agent; resolve actor to root
	root := t.TempDir()
	w, err := workspace.Init(root, "x")
	if err != nil {
		t.Fatal(err)
	}
	if err := store.CreateRole(w, agentid.RootID, team.Role{
		Name: "maintainer", Summary: "builds dacli", Scope: []string{"internal/**"},
	}); err != nil {
		t.Fatal(err)
	}
	ctx := &clikit.Ctx{Stdout: &bytes.Buffer{}, Stderr: &bytes.Buffer{}, Cwd: root}
	if err := cmdCodeowners(ctx, []string{"--owner", "acme"}); err != nil {
		t.Fatalf("cmdCodeowners: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(root, ".github", "CODEOWNERS"))
	if err != nil {
		t.Fatalf("CODEOWNERS not written: %v", err)
	}
	if !strings.Contains(string(data), "internal/ @acme/maintainer") {
		t.Fatalf("CODEOWNERS missing the role's ownership line:\n%s", data)
	}
}

// Never let the record lie: with no scoped role there is nothing to own, so the
// command errors rather than writing a hollow header-only file that reports success.
func TestCmdCodeownersRefusesWithNoScopedRole(t *testing.T) {
	unsetAgentEnv(t) // this suite may run as a dacli agent; resolve actor to root
	root := t.TempDir()
	w, err := workspace.Init(root, "x")
	if err != nil {
		t.Fatal(err)
	}
	if err := store.CreateRole(w, agentid.RootID, team.Role{Name: "vibes", Summary: "no scope"}); err != nil {
		t.Fatal(err)
	}
	ctx := &clikit.Ctx{Stdout: &bytes.Buffer{}, Stderr: &bytes.Buffer{}, Cwd: root}
	if err := cmdCodeowners(ctx, []string{"--owner", "acme"}); err == nil {
		t.Fatalf("cmdCodeowners must error when no role declares a scope, not write an empty CODEOWNERS")
	}
	if _, err := os.Stat(filepath.Join(root, ".github", "CODEOWNERS")); !os.IsNotExist(err) {
		t.Fatalf("a hollow CODEOWNERS must not be written when there is nothing to own")
	}
}
