package ghmirror

// dacli 224: roles emit a CODEOWNERS file. A real project routes review by
// mapping code areas to owning teams; dacli already carries exactly that mapping
// in its roles — each role's `scope` globs are the paths it owns. So `github
// codeowners` projects those role scopes into .github/CODEOWNERS, the planning
// artifact a hand-run repo would otherwise maintain by hand.
//
// The mapping is pure and unit-tested without gh or the filesystem: a role's
// scope glob → a CODEOWNERS pattern, owned by a team handle derived from the
// repo owner and the role name (@owner/role). Multiple roles owning one pattern
// share a single line (CODEOWNERS's own multi-owner form). CODEOWNERS resolves
// by LAST match, so patterns are emitted MOST-GENERAL FIRST — a broad
// `internal/` owner is overridden by a specific `internal/features/dashboard/`
// one, exactly the way CODEOWNERS is meant to be layered.

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mlnomadpy/dacli/internal/clikit"
	"github.com/mlnomadpy/dacli/internal/store"
	"github.com/mlnomadpy/dacli/internal/team"
	"github.com/mlnomadpy/dacli/internal/workspace"
)

// codeownersPath is where GitHub looks for the file (repo-root .github/). One
// place, so the writer and any future reader agree.
func codeownersPath(root string) string {
	return filepath.Join(root, ".github", "CODEOWNERS")
}

// ownerHandle renders the CODEOWNERS owner for a role: a GitHub team handle under
// the repo's owner org, @owner/role. Role names are single safe segments
// (store.CreateRole enforces it), so they are valid team-slug text.
func ownerHandle(org, role string) string {
	return "@" + org + "/" + role
}

// codeownersPattern converts a dacli scope glob to a CODEOWNERS pattern.
// CODEOWNERS uses gitignore-style matching where a directory prefix (kept with
// its trailing slash) already matches everything beneath it recursively, so
// dacli's trailing `**` ("any number of segments") is redundant and stripped —
// `internal/**` → `internal/`, which owns the directory tree. A bare `**` (or an
// empty glob) becomes `*` (every path). Any other glob passes through unchanged:
// the role scopes this repo uses are all `dir/**`, and a pattern CODEOWNERS
// cannot express is left as written rather than mistranslated into a wrong map.
func codeownersPattern(glob string) string {
	g := strings.TrimSpace(glob)
	if g == "" {
		return "*"
	}
	// Trim only the `**` (not the slash before it), so `internal/**` keeps its
	// directory-marking trailing slash → `internal/`.
	g = strings.TrimSuffix(g, "**")
	if g == "" {
		return "*"
	}
	return g
}

// codeownersEntry is one CODEOWNERS line: a path pattern and the ordered,
// de-duplicated owners that must review it.
type codeownersEntry struct {
	Pattern string
	Owners  []string
}

// codeownersEntries builds the CODEOWNERS lines from the roles: each role with a
// scope contributes its patterns, owned by its team handle. Owners for the same
// pattern are merged onto one line (deduped, first-seen order preserved).
// Patterns are returned MOST-GENERAL FIRST (shortest pattern first, then
// lexicographic) so a specific owner overrides a broad one under CODEOWNERS's
// last-match-wins rule. A role with no scope owns nothing and is skipped.
func codeownersEntries(roles []team.Role, org string) []codeownersEntry {
	var order []string
	byPattern := map[string][]string{}
	seen := map[string]map[string]bool{}
	for _, r := range roles {
		if r.Name == "" || len(r.Scope) == 0 {
			continue
		}
		owner := ownerHandle(org, r.Name)
		for _, glob := range r.Scope {
			pat := codeownersPattern(glob)
			if pat == "" {
				continue
			}
			if _, ok := seen[pat]; !ok {
				seen[pat] = map[string]bool{}
				order = append(order, pat)
			}
			if !seen[pat][owner] {
				seen[pat][owner] = true
				byPattern[pat] = append(byPattern[pat], owner)
			}
		}
	}
	sort.SliceStable(order, func(i, j int) bool {
		if len(order[i]) != len(order[j]) {
			return len(order[i]) < len(order[j])
		}
		return order[i] < order[j]
	})
	out := make([]codeownersEntry, 0, len(order))
	for _, pat := range order {
		out = append(out, codeownersEntry{Pattern: pat, Owners: byPattern[pat]})
	}
	return out
}

// codeownersDoc renders the CODEOWNERS file text: a generated-by header (so a
// human reading it knows it is projected from dacli roles, not hand-edited)
// followed by one `pattern owner…` line per entry. Pure — no gh, no I/O.
func codeownersDoc(entries []codeownersEntry) string {
	var b strings.Builder
	b.WriteString("# CODEOWNERS — generated by dacli from role scopes; the workspace is the source of truth.\n")
	b.WriteString("# Each line maps a path pattern to the role team(s) that own review of it.\n")
	b.WriteString("# Edit the roles (.dacli/roles/) and re-run `dacli github codeowners`, not this file.\n\n")
	for _, e := range entries {
		b.WriteString(e.Pattern + " " + strings.Join(e.Owners, " ") + "\n")
	}
	return b.String()
}

// cmdCodeowners writes .github/CODEOWNERS from the workspace roles. The owner org
// is --owner, or the linked project's repo owner. Writing a local file is not an
// outbound GitHub write, so — like template generation — it is not disclosure-
// gated; the file is committed and reviewed like any other repo artifact.
func cmdCodeowners(ctx *clikit.Ctx, args []string) error {
	w, _, err := clikit.OpenWorkspace(ctx)
	if err != nil {
		return err
	}
	f, _ := clikit.ParseFlags(args)
	if err := f.Reject("owner", "stdout", "dry-run"); err != nil {
		return err
	}
	dry := f.Bool("dry-run")
	org, err := codeownersOwner(w, f)
	if err != nil {
		return err
	}
	roles, err := store.LoadRoles(w)
	if err != nil {
		return err
	}
	entries := codeownersEntries(roles, org)
	// Never let the record lie: writing a header-only CODEOWNERS would report
	// success while owning nothing. If no role declares a scope, say so and write
	// nothing rather than a hollow file.
	if len(entries) == 0 {
		return fmt.Errorf("no role declares a scope — nothing to own; add `scope:` globs to roles in .dacli/roles/ first")
	}
	doc := codeownersDoc(entries)
	if f.Bool("stdout") {
		fmt.Fprint(ctx.Stdout, doc)
		return nil
	}
	path := codeownersPath(w.Root)
	// --dry-run previews the exact file the write below would produce (same
	// entries, same rendered doc) without touching the filesystem (task 294).
	if dry {
		fmt.Fprintf(ctx.Stdout, "dry-run: would write %s — %d owned pattern(s) from %d role(s); nothing was written:\n", path, len(entries), len(roles))
		fmt.Fprint(ctx.Stdout, doc)
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(doc), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(ctx.Stdout, "wrote %s — %d owned pattern(s) from %d role(s)\n", path, len(entries), len(roles))
	return nil
}

// codeownersOwner resolves the owner org for the team handles: an explicit
// --owner wins; otherwise a positional project arg's linked repo supplies it. A
// project that is not linked (and no --owner) is a usage error naming both fixes,
// so the command never silently emits handles under a wrong or empty org.
func codeownersOwner(w *workspace.Workspace, f *clikit.Flags) (string, error) {
	if org := strings.TrimSpace(f.Get("owner")); org != "" {
		return org, nil
	}
	if len(f.Pos) == 0 {
		return "", clikit.Usagef("usage: dacli github codeowners <project> | dacli github codeowners --owner <org>")
	}
	p, err := store.LoadProject(w, f.Pos[0])
	if err != nil {
		return "", err
	}
	repo, _ := p.Doc.Front.Get("github_repo")
	if repo == "" {
		return "", clikit.Usagef("project %s is not linked — `dacli github link %s` first, or pass --owner <org>", p.Slug, p.Slug)
	}
	owner := ownerOf(repo)
	if owner == "" {
		return "", fmt.Errorf("cannot derive owner from repo %q — expected owner/name", repo)
	}
	return owner, nil
}
